#pragma once

#include <array>
#include "enums.h"

using namespace std;

static const array<int, 10> CSM_COLORS_DIVERGING {
    COLOR_DIVERGING_CRIMSON,
    COLOR_DIVERGING_SIENNA,
    COLOR_DIVERGING_ORANGE,
    COLOR_DIVERGING_TAN,
    COLOR_DIVERGING_KHAKI,
    COLOR_DIVERGING_ALICE_BLUE,
    COLOR_DIVERGING_LIGHT_BLUE,
    COLOR_DIVERGING_CORNFLOWER_BLUE,
    COLOR_DIVERGING_STEEL_BLUE,
    COLOR_DIVERGING_ROYAL_BLUE
};

enum ColorSequenceMode
{
    CSM_BLACK,
    CSM_DIVERGING
};


